server:
  port: 8080
spring:
  cloud:
    gateway:
#      routes:
#        - id: wjy_route
#          uri: http://www.ityouknow.com
#          predicates:
#            - Path=/spring-cloud
#            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
      routes:
        - id: add_request_parameter_route
#          uri: http://localhost:9001
          #格式为：lb://应用注册服务名
          uri: lb://spring-cloud-provider
          filters:
#            - AddRequestParameter=foo, bar
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
          predicates:
            - Method=GET
      discovery:
        locator:
          enabled: true
  application:
    name: spring-cloud-gateway
  redis:
    host: 192.168.56.10
    password:
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug